sudo: false
dist: trusty

language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cp ci/testsettings.py ProjectQuincy/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> ProjectQuincy/local_settings.py

script:
  - py.test --cov

sevices:
  - mysql  

after_success:
  - codecov