# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttitle',
            name='assignment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.AssignmentType'),
        ),
        migrations.AlterField(
            model_name='assignmenttitle',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='assignmenttype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='orgevolution',
            name='org_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_1', to='activities.Organization'),
        ),
        migrations.AlterField(
            model_name='orgevolution',
            name='org_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_2', to='activities.Organization'),
        ),
        migrations.AlterField(
            model_name='orgevolution',
            name='org_evolution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.OrgEvolutionType'),
        ),
        migrations.AlterField(
            model_name='orgevolutiontype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='roletitle',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='name',
            field=models.CharField(max_length=765),
        ),
    ]
