# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='entry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.CharField(max_length=765),
        ),
    ]
