# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enclosure',
            name='enclosed_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_2', to='communication.Letter'),
        ),
    ]
