# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='occupationtitle',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='occupationtype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='residencetype',
            name='name',
            field=models.CharField(max_length=765),
        ),
    ]
