# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Individual'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occupation_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.OccupationTitle'),
        ),
        migrations.AlterField(
            model_name='occupationtitle',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='occupationtype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='individual_id_1',
            field=models.ForeignKey(db_column=b'individual_id_1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_1', to='people.Individual'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='individual_id_2',
            field=models.ForeignKey(db_column=b'individual_id_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_2', to='people.Individual'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.RelationshipType'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.CharField(max_length=765),
        ),
        migrations.AlterField(
            model_name='residence',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Individual'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Location'),
        ),
        migrations.AlterField(
            model_name='residencetype',
            name='name',
            field=models.CharField(max_length=765),
        ),
    ]
